language: go

go:
- 1.15.5

env:
- GO111MODULE=auto

script:
  - go test -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
git:
  depth: 1

branches:
  only:
    - release-2.0.0